apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  name: nginx-pvc
  namespace: developer
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
