apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-data
        persistentVolumeClaim:
         claimName: "nginx-pvc"
      nodeSelector:
      containers:
      - image: quay.io/linxianer12/todoapp:1.0.12
        name: nginx
        resources: {}
        volumeMounts:
        - name: nginx-data
          mountPath: /var/www/html

        
status: {}
