apiVersion: v1
kind: Pod
metadata:
  # ชื่อของ Pod ที่จะได้มา
  name: security-context-demo
spec:
  containers:
  # ชื่อของ Container ที่ผูกภายใน Pod
  - name: yes-ping-pod
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      capabilities:
        add: ["NET_RAW"]
  